### ISSUE TITLE
CORS problem in KrakenD 1.0.0

### ISSUE THREAD

**Issue by melody-dev** [devopsfaith/krakend-cors#10]
I already deploy Kraken D image 0.9.0 (with Docker command) for a while, everything work as well and properly.

But when i try to upgrade Krakend D image to version 1.0.0 with the same configuration and testing. I found CORS problem occurred.

What should i do for workaround or investigate this problem ?

This is my CORS configuration

````
"github_com/devopsfaith/krakend-cors": {
    "allow_origins": [
        "*"
    ],
    "allow_headers": [
        "Content-Length",
        "Authorization",
        "Content-Type"
    ],
    "expose_headers": [
        "Content-Length"
    ]
}
````

**Comment by taik0** [comment]
Hi @melody-dev and welcome to the KrakenD community!

Can you share the error message and the steps to reproduce it?

**Comment by melody-dev** [comment]
Hi @taik0 

First i've deploy KrakenD with separate image version

1. https://api090.foo.com this url use KrakenD version 0.9.0
2. https://api100.foo.com this url use KrakenD version 1.0.0

Both url use the same configuration and deploy to Google Compute Engine in the same VM (separate by Nginx and signed SSL certificate with Let's encrypted).

Second, the step to reproduce, i've try with 2 method

1. Test call from https://www.test-cors.org/ 
    with url https://api090.foo.com the response look properly as expectation
    with url https://api100.foo.com the response has error with Fired XHR event: error

2. Test call from javascript (use XMLHttpRequest)
    with url https://api090.foo.com everything work as properly
    with url https://api100.foo.com after execute request the error will occurred error message like below
    > Access to XMLHttpRequest at 'https://api100.foo.com/foo' from origin 'https://bar.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header containers multiple values '*, https://foo.com, *', foo.com/' but only one is allowed.

**Comment by thinkingmik** [comment]
Any news about this issue?

I have the same blocking issue.

**Comment by taik0** [comment]
I'm still testing this issue, but `rs/cors` (the library used) uses `http.Header.Set` that replaces any existing header with the same key so looks like it's your backed the one that's adding the duplicated header back?
From 0.9 to 1.0 we started to use `rs/cors` (like the mux adapter does) since the gin cors adapter has a lot of problems and does not comply with the CORS RFC.

**Comment by kpacha** [comment]
mmm... I think there is a problem in the flow you are trying to achieve: **the CORS layer should be placed where the browser is connecting, aka the gateway. the communication between the gateway and the backends is not using CORS.**

so the flow should be:

- the browser sees a JS call outside the original domain and intercepts it.
- the browser automatically generates an OPTIONS request to the target asking for permission to do a cross origin request
- the target (gateway) deals with this request without talking with the backends
- if the request is denied, the browser cancels the intercepted call and returns an error
- with the ok from the gateway, the browser resumes the intercepted call to the gateway
- the gateway processes the call as usual, passing it to the selected backend(s) and returning the response to the client

...and the backend never learns that the requests are coming from a browser at a different domain.

**Comment by thinkingmik** [comment]
Hi,

> it looks like it's your backend the one that's adding the duplicated header back?

Yes it's the backend that adds another `Access-Control-Allow-Origin` header (in my case the nodejs service with CORS enabled). Disabling CORS in the backend service resolve the issue.

> the CORS layer should be placed where the browser is connecting, aka the gateway. the communication between the gateway and the backends is not using CORS.

I agree with you. So I think it's not a bug of KrakenD, it's only a different behavior of managing headers in the 1.0.0 version of KrakenD because now it uses the `rs/cors` library.

Moreover I found this issue [https://github.com/rs/cors/issues/45](https://github.com/rs/cors/issues/45) that explains what probably happens.
